/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    questions: Question;
    plans: Plan;
    segments: Segment;
    recommendations: Recommendation;
    Questionnaires: Questionnaire;
    pages: Page;
    'page-categories': PageCategory;
    links: Link;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    questions: QuestionsSelect<false> | QuestionsSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    segments: SegmentsSelect<false> | SegmentsSelect<true>;
    recommendations: RecommendationsSelect<false> | RecommendationsSelect<true>;
    Questionnaires: QuestionnairesSelect<false> | QuestionnairesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'page-categories': PageCategoriesSelect<false> | PageCategoriesSelect<true>;
    links: LinksSelect<false> | LinksSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions".
 */
export interface Question {
  id: string;
  questionText: string;
  dimensionId: 'provider' | 'cost' | 'health' | 'prescriptions' | 'benefits';
  questionType: 'rating' | 'multipleChoice' | 'boolean';
  /**
   * Additional context or help text for this question
   */
  description?: string | null;
  options?:
    | {
        label: string;
        value: string;
        basePoints: number;
        segmentScores: {
          minimizer: number;
          protector: number;
          preventer: number;
          manager: number;
          loyalist: number;
        };
        id?: string | null;
      }[]
    | null;
  order: number;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Medicare plan types and their characteristics
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: string;
  name: string;
  planType: 'medicareAdvantage' | 'medicareSupplement' | 'medicareAdvantageWellness' | 'medicareAdvantageCondition';
  /**
   * Brief overview of the plan (1-2 sentences)
   */
  shortDescription: string;
  /**
   * Detailed description of the plan
   */
  longDescription?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  keyFeatures: {
    feature: string;
    id?: string | null;
  }[];
  bestFor: {
    point: string;
    id?: string | null;
  }[];
  considerations: {
    point: string;
    id?: string | null;
  }[];
  coverage: {
    monthlyPremiumRange: {
      min: number;
      max: number;
    };
    annualDeductibleRange: {
      min: number;
      max: number;
    };
    networkRestrictions: 'none' | 'low' | 'moderate' | 'high';
  };
  additionalBenefits?: {
    dental?: boolean | null;
    vision?: boolean | null;
    hearing?: boolean | null;
    fitness?: boolean | null;
    transportation?: boolean | null;
    mealDelivery?: boolean | null;
    other?:
      | {
          benefitName: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * User segments for Medicare plan recommendations
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "segments".
 */
export interface Segment {
  id: string;
  name: string;
  segmentId: 'minimizer' | 'protector' | 'preventer' | 'manager' | 'loyalist';
  description: string;
  characteristics: {
    trait: string;
    id?: string | null;
  }[];
  scoringCriteria: {
    dimension: 'provider' | 'cost' | 'health' | 'prescriptions' | 'benefits';
    /**
     * Weight between 0 and 1
     */
    weight: number;
    /**
     * Ideal score for this dimension (1-5)
     */
    preferredScore: number;
    id?: string | null;
  }[];
  planAffinities: {
    planType: string | Plan;
    /**
     * How well this segment matches with the plan type (0-100)
     */
    affinityScore: number;
    reasonings?:
      | {
          reason: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  matchThresholds: {
    highConfidence: number;
    mediumConfidence: number;
    lowConfidence: number;
  };
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * Medicare plan recommendations and results
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recommendations".
 */
export interface Recommendation {
  id: string;
  user: string | User;
  userPreferences: {
    doctorChoice: {
      value: number;
      comments?: string | null;
    };
    managedCare: {
      value: number;
      comments?: string | null;
    };
    domesticTravel: {
      value: number;
      comments?: string | null;
    };
    yearlyMaximums: {
      value: number;
      comments?: string | null;
    };
    monthlyPremiums: {
      value: number;
      comments?: string | null;
    };
    prescriptionPlans: {
      value: number;
      comments?: string | null;
    };
    dentalVision: {
      value: number;
      comments?: string | null;
    };
  };
  scoringResults: {
    dimensionScores: {
      provider: number;
      cost: number;
      health: number;
      prescriptions: number;
      benefits: number;
    };
    segmentMatches: {
      segment: string | Segment;
      score: number;
      confidence: number;
      id?: string | null;
    }[];
  };
  recommendations: {
    plan: string | Plan;
    matchScore: number;
    isPrimary?: boolean | null;
    reasonsForMatch?:
      | {
          reason: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  status: 'active' | 'archived';
  metadata: {
    createdAt: string;
    lastViewed?: string | null;
    source?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Questionnaires".
 */
export interface Questionnaire {
  id: string;
  responses:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'started' | 'completed';
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * This will be used as the URL for this page
   */
  slug: string;
  /**
   * Select the primary category/pillar for this page
   */
  category: string | PageCategory;
  /**
   * Select a parent page if this page should be nested under another page
   */
  parentPage?: (string | null) | Page;
  /**
   * Custom breadcrumb path (leave empty to use the default path)
   */
  breadcrumb?:
    | {
        label: string;
        page?: (string | null) | Page;
        id?: string | null;
      }[]
    | null;
  pageTemplate: 'standard' | 'landing' | 'comparison' | 'faq';
  /**
   * Controls visibility in navigation
   */
  isVisible?: boolean | null;
  /**
   * Controls sorting within category
   */
  order?: number | null;
  content?:
    | (
        | {
            text: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            image: string | Media;
            caption?: string | null;
            size?: ('small' | 'normal' | 'large' | 'fullWidth') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            headline: string;
            text?: string | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
        | {
            heading: string;
            benefits?:
              | {
                  benefit: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'benefitsList';
          }
        | {
            heading: string;
            faqs?:
              | {
                  question: string;
                  answer: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            heading: string;
            plans?:
              | {
                  planName: string;
                  planFeatures?:
                    | {
                        feature: string;
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'planComparisonTable';
          }
      )[]
    | null;
  /**
   * Select pages that are related to this content
   */
  relatedPages?: (string | Page)[] | null;
  /**
   * Controls how search engines understand this page in relation to similar content
   */
  canonicalType?: ('self' | 'other' | 'none') | null;
  /**
   * Select the canonical version of this page
   */
  canonicalPage?: (string | null) | Page;
  /**
   * Enter external canonical URL (only if "Other Page" is not selected)
   */
  canonicalURL?: string | null;
  /**
   * Prevent search engines from indexing this page
   */
  noIndex?: boolean | null;
  seo?: {
    /**
     * Override the default page title for search engines (leave blank to use page title)
     */
    metaTitle?: string | null;
    /**
     * Brief description of this page for search results and social sharing
     */
    metaDescription?: string | null;
    /**
     * Image for social sharing (Facebook, Twitter, etc.)
     */
    ogImage?: (string | null) | Media;
    /**
     * Comma-separated keywords (less important for modern SEO)
     */
    keywords?: string | null;
  };
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-categories".
 */
export interface PageCategory {
  id: string;
  name: string;
  /**
   * URL-friendly version of the category name (no spaces or special characters)
   */
  slug: string;
  description?: string | null;
  /**
   * Select a parent category if this is a subcategory
   */
  parentCategory?: (string | null) | PageCategory;
  /**
   * Controls the sorting order of categories
   */
  order?: number | null;
  icon?: (string | null) | Media;
  /**
   * Check if this is a main content pillar for SEO purposes
   */
  isMainPillar?: boolean | null;
  showInMainNav?: boolean | null;
  showInFooter?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links".
 */
export interface Link {
  id: string;
  label: string;
  linkType: 'internal' | 'external' | 'file' | 'email';
  /**
   * Select the page to link to
   */
  internalPage?: (string | null) | Page;
  /**
   * Enter the full URL, including https://
   */
  url?: string | null;
  /**
   * Enter the email address
   */
  emailAddress?: string | null;
  /**
   * Open link in a new browser tab
   */
  openInNewTab?: boolean | null;
  /**
   * Where this link will be used
   */
  linkCategory: 'main-navigation' | 'footer' | 'sidebar' | 'in-content' | 'resource';
  /**
   * If this is a child link in a dropdown, select the parent link
   */
  parentLink?: (string | null) | Link;
  /**
   * Controls the display order
   */
  order?: number | null;
  /**
   * Optional icon for the link
   */
  icon?: (string | null) | Media;
  /**
   * Optional description text (for mega-menus or tooltips)
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'questions';
        value: string | Question;
      } | null)
    | ({
        relationTo: 'plans';
        value: string | Plan;
      } | null)
    | ({
        relationTo: 'segments';
        value: string | Segment;
      } | null)
    | ({
        relationTo: 'recommendations';
        value: string | Recommendation;
      } | null)
    | ({
        relationTo: 'Questionnaires';
        value: string | Questionnaire;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'page-categories';
        value: string | PageCategory;
      } | null)
    | ({
        relationTo: 'links';
        value: string | Link;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions_select".
 */
export interface QuestionsSelect<T extends boolean = true> {
  questionText?: T;
  dimensionId?: T;
  questionType?: T;
  description?: T;
  options?:
    | T
    | {
        label?: T;
        value?: T;
        basePoints?: T;
        segmentScores?:
          | T
          | {
              minimizer?: T;
              protector?: T;
              preventer?: T;
              manager?: T;
              loyalist?: T;
            };
        id?: T;
      };
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  planType?: T;
  shortDescription?: T;
  longDescription?: T;
  keyFeatures?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  bestFor?:
    | T
    | {
        point?: T;
        id?: T;
      };
  considerations?:
    | T
    | {
        point?: T;
        id?: T;
      };
  coverage?:
    | T
    | {
        monthlyPremiumRange?:
          | T
          | {
              min?: T;
              max?: T;
            };
        annualDeductibleRange?:
          | T
          | {
              min?: T;
              max?: T;
            };
        networkRestrictions?: T;
      };
  additionalBenefits?:
    | T
    | {
        dental?: T;
        vision?: T;
        hearing?: T;
        fitness?: T;
        transportation?: T;
        mealDelivery?: T;
        other?:
          | T
          | {
              benefitName?: T;
              description?: T;
              id?: T;
            };
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "segments_select".
 */
export interface SegmentsSelect<T extends boolean = true> {
  name?: T;
  segmentId?: T;
  description?: T;
  characteristics?:
    | T
    | {
        trait?: T;
        id?: T;
      };
  scoringCriteria?:
    | T
    | {
        dimension?: T;
        weight?: T;
        preferredScore?: T;
        id?: T;
      };
  planAffinities?:
    | T
    | {
        planType?: T;
        affinityScore?: T;
        reasonings?:
          | T
          | {
              reason?: T;
              id?: T;
            };
        id?: T;
      };
  matchThresholds?:
    | T
    | {
        highConfidence?: T;
        mediumConfidence?: T;
        lowConfidence?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recommendations_select".
 */
export interface RecommendationsSelect<T extends boolean = true> {
  user?: T;
  userPreferences?:
    | T
    | {
        doctorChoice?:
          | T
          | {
              value?: T;
              comments?: T;
            };
        managedCare?:
          | T
          | {
              value?: T;
              comments?: T;
            };
        domesticTravel?:
          | T
          | {
              value?: T;
              comments?: T;
            };
        yearlyMaximums?:
          | T
          | {
              value?: T;
              comments?: T;
            };
        monthlyPremiums?:
          | T
          | {
              value?: T;
              comments?: T;
            };
        prescriptionPlans?:
          | T
          | {
              value?: T;
              comments?: T;
            };
        dentalVision?:
          | T
          | {
              value?: T;
              comments?: T;
            };
      };
  scoringResults?:
    | T
    | {
        dimensionScores?:
          | T
          | {
              provider?: T;
              cost?: T;
              health?: T;
              prescriptions?: T;
              benefits?: T;
            };
        segmentMatches?:
          | T
          | {
              segment?: T;
              score?: T;
              confidence?: T;
              id?: T;
            };
      };
  recommendations?:
    | T
    | {
        plan?: T;
        matchScore?: T;
        isPrimary?: T;
        reasonsForMatch?:
          | T
          | {
              reason?: T;
              id?: T;
            };
        id?: T;
      };
  status?: T;
  metadata?:
    | T
    | {
        createdAt?: T;
        lastViewed?: T;
        source?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Questionnaires_select".
 */
export interface QuestionnairesSelect<T extends boolean = true> {
  responses?: T;
  status?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  parentPage?: T;
  breadcrumb?:
    | T
    | {
        label?: T;
        page?: T;
        id?: T;
      };
  pageTemplate?: T;
  isVisible?: T;
  order?: T;
  content?:
    | T
    | {
        text?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              headline?: T;
              text?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        benefitsList?:
          | T
          | {
              heading?: T;
              benefits?:
                | T
                | {
                    benefit?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              heading?: T;
              faqs?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        planComparisonTable?:
          | T
          | {
              heading?: T;
              plans?:
                | T
                | {
                    planName?: T;
                    planFeatures?:
                      | T
                      | {
                          feature?: T;
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  relatedPages?: T;
  canonicalType?: T;
  canonicalPage?: T;
  canonicalURL?: T;
  noIndex?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        keywords?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-categories_select".
 */
export interface PageCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parentCategory?: T;
  order?: T;
  icon?: T;
  isMainPillar?: T;
  showInMainNav?: T;
  showInFooter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links_select".
 */
export interface LinksSelect<T extends boolean = true> {
  label?: T;
  linkType?: T;
  internalPage?: T;
  url?: T;
  emailAddress?: T;
  openInNewTab?: T;
  linkCategory?: T;
  parentLink?: T;
  order?: T;
  icon?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}